[workspace]

resolver = "3"

members = ["qw"]

default-members = ["qw"]

[workspace.package]
edition = "2024"
version = "0.7.0"

[workspace.dependencies]
Inflector = "0.11"
anyhow = "1.0"
chrono = "0.4"
comfy-table = "7.2"
dialoguer = "0.12"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
tempfile = "3"
toml = "1.1"


sercli = { path = "../sercli/sercli" }
# sercli = "0.4.0"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls"] }
testcontainers-modules = { version = "0.11", features = ["postgres"] }
tokio = { version = "1", features = ["full"] }
