[workspace]

resolver = "3"

members = ["qw"]

default-members = ["qw"]

[workspace.package]
edition = "2024"
version = "0.1.1"

[workspace.dependencies]
anyhow = "1.0"
comfy-table = "7.2.2"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
toml = "1.1"

sercli = { path = "../sercli/sercli" }
